### ISSUE TITLE
get size function

### ISSUE THREAD

**Issue by PandaWhoCodes** [BARATH-BS/Web-Site-Analyzer#1]
What does this function do ?

```
def get_size(url):
    """
    :param url: url of the site
    :return: size of the site
    """
    return url

```

**Comment by PandaWhoCodes** [comment]
never mind saw the commented code

**Comment by BARATH-BS** [comment]
> never mind saw the commented code

Sir, I have tried to implement it, but there was an issue, that why I had just returned the url.
